// Generated by designlang v7.0.0
// Source: https://fluid.glass/
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF0B1012)
    val SurfaceDefault = Color(0xFFF3F0EC)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF0B1012)
    val NeutralN100 = Color(0xFF212325)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF000000)
    val NeutralN400 = Color(0xFFF3F0EC)
    val BackgroundBg0 = Color(0xFFF3F0EC)
    val BackgroundBg1 = Color(0xFF212325)
    val BackgroundBg2 = Color(0xFF0B1012)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF212325)
    val TextText2 = Color(0xFFFFFFFF)
    val SpacingS0 = 2.dp
    val SpacingS1 = 24.dp
    val SpacingS2 = 48.dp
    val SpacingS3 = 56.dp
    val SpacingS4 = 64.dp
    val SpacingS5 = 72.dp
    val SpacingS6 = 96.dp
    val SpacingS7 = 120.dp
    val SpacingS8 = 128.dp
    val SpacingS9 = 133.dp
    val SpacingS10 = 144.dp
    val SpacingS11 = 262.dp
    val SpacingS12 = 360.dp
    val SpacingS13 = 367.dp
    val RadiusR0 = 16.dp
}
