// Generated by designlang v7.0.0
// Source: https://fluid.glass/
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF0B1012);
  static const Color surfaceDefault = Color(0xFFF3F0EC);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 2;
  static const double spacingS1 = 24;
  static const double spacingS2 = 48;
  static const double spacingS3 = 56;
  static const double spacingS4 = 64;
  static const double spacingS5 = 72;
  static const double spacingS6 = 96;
  static const double spacingS7 = 120;
  static const double spacingS8 = 128;
  static const double spacingS9 = 133;
  static const double spacingS10 = 144;
  static const double spacingS11 = 262;
  static const double spacingS12 = 360;
  static const double spacingS13 = 367;
  static const double radiusR0 = 16;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF0B1012);
  static const Color neutralN100 = Color(0xFF212325);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF000000);
  static const Color neutralN400 = Color(0xFFF3F0EC);
  static const Color backgroundBg0 = Color(0xFFF3F0EC);
  static const Color backgroundBg1 = Color(0xFF212325);
  static const Color backgroundBg2 = Color(0xFF0B1012);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF212325);
  static const Color textText2 = Color(0xFFFFFFFF);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
