// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://fluid.glass/
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x0B1012)
  static let surfaceDefault = Color(hex: 0xF3F0EC)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 2
  static let spacingS1: CGFloat = 24
  static let spacingS2: CGFloat = 48
  static let spacingS3: CGFloat = 56
  static let spacingS4: CGFloat = 64
  static let spacingS5: CGFloat = 72
  static let spacingS6: CGFloat = 96
  static let spacingS7: CGFloat = 120
  static let spacingS8: CGFloat = 128
  static let spacingS9: CGFloat = 133
  static let spacingS10: CGFloat = 144
  static let spacingS11: CGFloat = 262
  static let spacingS12: CGFloat = 360
  static let spacingS13: CGFloat = 367

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 16
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x0B1012)
  static let neutralN100 = Color(hex: 0x212325)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x000000)
  static let neutralN400 = Color(hex: 0xF3F0EC)
  static let backgroundBg0 = Color(hex: 0xF3F0EC)
  static let backgroundBg1 = Color(hex: 0x212325)
  static let backgroundBg2 = Color(hex: 0x0B1012)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x212325)
  static let textText2 = Color(hex: 0xFFFFFF)
}

// typography.body: family=Aeonik Pro size=51.2px weight=400 lineHeight=51.2px
